-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE REMITTANCE_INCLUSION;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.CORRIDORS (
  CORRIDOR_ID VARCHAR(20) NOT NULL, SOURCE_COUNTRY VARCHAR(50), DEST_COUNTRY VARCHAR(50), CURRENCY_PAIR VARCHAR(10), AVG_TRANSFER_USD FLOAT, MONTHLY_VOLUME_M FLOAT, FEE_PCT FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TRANSFERS (
  TRANSFER_ID VARCHAR(30) NOT NULL, CORRIDOR_ID VARCHAR(20), SENDER_ID VARCHAR(20), AMOUNT_USD FLOAT, FX_RATE FLOAT, FEE FLOAT, SEND_DATE TIMESTAMP, RECEIVE_DATE TIMESTAMP, CHANNEL VARCHAR(30), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
  CUSTOMER_ID VARCHAR(20) NOT NULL, CUSTOMER_NAME VARCHAR(200), SEGMENT VARCHAR(30), REGION VARCHAR(50), REGISTRATION_DATE DATE, TOTAL_ACCOUNTS INT, LIFETIME_VALUE FLOAT, RISK_SCORE FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PARTNERS (
  PARTNER_ID VARCHAR(20) NOT NULL, PARTNER_NAME VARCHAR(200), COUNTRY VARCHAR(50), PARTNER_TYPE VARCHAR(30), TRANSACTION_VOLUME FLOAT, FEE_STRUCTURE VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
