-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for Financial Inclusion & Micro-lending Analytics
-- ============================================================================
USE DATABASE FINANCIAL_INCLUSION;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.BORROWER_PROFILES (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.REMITTANCE_HISTORY (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WALLET_BEHAVIOR (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TELCO_SIGNALS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.LOAN_PORTFOLIO (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.REPAYMENT_RECORDS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.BSP_INCLUSION_DATA (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

