-- Generated from generator/demo_specs/aws-philippines-remittance-inclusion.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-remittance-inclusion
-- This is the schema that is actually deployed for PH_REMITTANCE_INCLUSION.

-- Alerts fire on the bottom tail of Rural Coverage
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_RURAL_COVERAGE) AS T
  FROM RAW.WALLET_BEHAVIOR
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_RURAL_COVERAGE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_RURAL_COVERAGE), 2) AS AVG_RURAL_COVERAGE,
  ROUND(AVG(f.KPI_AVG_REMITTANCE), 2) AS AVG_REMITTANCE,
  ROUND(AVG(f.KPI_AGENT_UPTIME), 2) AS AVG_AGENT_UPTIME,
  ROUND(AVG(f.KPI_LIQUIDITY_ISSUES), 2) AS AVG_LIQUIDITY_ISSUES,
  ROUND(AVG(f.KPI_REVENUE_AGENT), 2) AS AVG_REVENUE_AGENT
FROM RAW.WALLET_BEHAVIOR f
JOIN RAW.BSP_INCLUSION_DATA e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_RURAL_COVERAGE), 2) AS AVG_RURAL_COVERAGE,
  ROUND(AVG(f.KPI_AVG_REMITTANCE), 2) AS AVG_REMITTANCE,
  ROUND(AVG(f.KPI_AGENT_UPTIME), 2) AS AVG_AGENT_UPTIME,
  ROUND(AVG(f.KPI_LIQUIDITY_ISSUES), 2) AS AVG_LIQUIDITY_ISSUES,
  ROUND(AVG(f.KPI_REVENUE_AGENT), 2) AS AVG_REVENUE_AGENT
FROM RAW.WALLET_BEHAVIOR f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_RURAL_COVERAGE) AS KPI_RURAL_COVERAGE, AVG(KPI_AVG_REMITTANCE) AS KPI_AVG_REMITTANCE, AVG(KPI_AGENT_UPTIME) AS KPI_AGENT_UPTIME, AVG(KPI_LIQUIDITY_ISSUES) AS KPI_LIQUIDITY_ISSUES, AVG(KPI_REVENUE_AGENT) AS KPI_REVENUE_AGENT FROM RAW.WALLET_BEHAVIOR),
     en AS (SELECT SUM(KPI_UNBANKED_ONBOARDED) AS KPI_UNBANKED_ONBOARDED, SUM(KPI_AGENT_NETWORK) AS KPI_AGENT_NETWORK FROM RAW.BSP_INCLUSION_DATA)
  SELECT 1 AS SORT_ORDER, 'Unbanked Onboarded' AS TITLE, KPI_UNBANKED_ONBOARDED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_UNBANKED_ONBOARDED) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Agent Network' AS TITLE, KPI_AGENT_NETWORK AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_AGENT_NETWORK) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Rural Coverage' AS TITLE, KPI_RURAL_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RURAL_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Avg Remittance' AS TITLE, KPI_AVG_REMITTANCE AS VALUE_NUM, '₱' || LTRIM(TO_VARCHAR(CAST(ROUND((KPI_AVG_REMITTANCE)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Agent Uptime' AS TITLE, KPI_AGENT_UPTIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AGENT_UPTIME)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Liquidity Issues' AS TITLE, KPI_LIQUIDITY_ISSUES AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_LIQUIDITY_ISSUES)) AS DECIMAL(38,0))) || '/day' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Revenue/Agent' AS TITLE, KPI_REVENUE_AGENT AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_REVENUE_AGENT) / 1000)) AS DECIMAL(38,0))) || 'K' || '/mo' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
