-- ============================================================================
-- 99_RESET.SQL — Reset Financial Inclusion & Micro-lending Analytics to clean demo state
-- ============================================================================
USE DATABASE FINANCIAL_INCLUSION;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_FEATURES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_APPLICANTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_NOTIFY_APPROVALS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.ALT_CREDIT_FEATURES REFRESH;
ALTER DYNAMIC TABLE CURATED.PORTFOLIO_HEALTH REFRESH;
ALTER DYNAMIC TABLE CURATED.INCLUSION_METRICS REFRESH;
ALTER DYNAMIC TABLE CURATED.MODEL_MONITORING REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM FINANCIAL_INCLUSION.RAW.BORROWER_PROFILES → 380000
-- SELECT COUNT(*) FROM FINANCIAL_INCLUSION.RAW.REMITTANCE_HISTORY → 2800000
-- SELECT COUNT(*) FROM FINANCIAL_INCLUSION.RAW.LOAN_PORTFOLIO WHERE BORROWER_UNBANKED = TRUE → ~247000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_NOTIFY_APPROVALS RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_APPLICANTS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FEATURES RESUME;
